# Generated by Django 4.0.3 on 2022-04-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_professional', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('adress', models.CharField(help_text='Required', max_length=255, verbose_name='adress')),
                ('working_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('urgency_rate', models.IntegerField(default=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='module1.client')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Not required', verbose_name='description')),
                ('number_of_photos', models.IntegerField(default=1)),
                ('paper_type', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('photo_format', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('regular_price', models.FloatField(help_text='Максимально 10 цифр', verbose_name='Regular price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='module1.order')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='module1.facility_type'),
        ),
    ]
