# Generated by Django 4.0.3 on 2022-04-24 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_remove_services_order_orderservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility_type',
            options={'verbose_name': 'Филиалы и киоски', 'verbose_name_plural': 'Филиалы и киоски'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='module1.facility_type'),
        ),
        migrations.AlterField(
            model_name='services',
            name='paper_type',
            field=models.CharField(default=None, help_text='Required', max_length=255, verbose_name='paper type'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_format',
            field=models.CharField(default=None, help_text='Required', max_length=255, verbose_name='photo format'),
        ),
    ]
