# Generated by Django 4.0.3 on 2022-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_facility_type_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='paper_type',
            field=models.CharField(blank=True, help_text='Required', max_length=255, verbose_name='paper type'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_format',
            field=models.CharField(blank=True, help_text='Required', max_length=255, verbose_name='photo format'),
        ),
    ]
