# Generated by Django 4.0.3 on 2022-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_alter_services_paper_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='photos/photo-roll.png', help_text='Upload a product image', upload_to='photos/', verbose_name='image'),
        ),
    ]
