# Generated by Django 4.0.3 on 2022-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('good', 'Goods'), ('service', 'Service')], default='good', max_length=32),
        ),
    ]
