# Generated by Django 4.0.3 on 2022-04-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_services_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservice',
            options={'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказов'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='urgency_rate',
        ),
        migrations.RemoveField(
            model_name='services',
            name='number_of_photos',
        ),
        migrations.RemoveField(
            model_name='services',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='services',
            name='photo_format',
        ),
        migrations.AddField(
            model_name='orderservice',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='module1.facility_type'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='number_of_photos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='paper_type',
            field=models.CharField(blank=True, help_text='Required', max_length=255, verbose_name='paper type'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='photo_format',
            field=models.CharField(blank=True, help_text='Required', max_length=255, verbose_name='photo format'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='price',
            field=models.FloatField(default=None, help_text='Максимально 10 цифр', verbose_name='total price'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='urgency_rate',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('good', 'Goods'), ('service', 'Services')], default='good', max_length=32),
        ),
    ]
