# Generated by Django 4.0.3 on 2022-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_alter_orderservice_options_remove_order_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='available',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='paper_type',
            field=models.CharField(blank=True, default=None, help_text='Required', max_length=255, verbose_name='paper type'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='photo_format',
            field=models.CharField(blank=True, default=None, help_text='Required', max_length=255, verbose_name='photo format'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='urgency_rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, help_text='Not required', verbose_name='Описание'),
        ),
    ]
