# Generated by Django 4.0.3 on 2022-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_orderservice_available_alter_orderservice_paper_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='available',
        ),
        migrations.AddField(
            model_name='services',
            name='available',
            field=models.IntegerField(default=None),
        ),
    ]
