# Generated by Django 4.0.3 on 2022-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0010_remove_orderservice_available_services_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
