# Generated by Django 4.0.3 on 2022-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0011_alter_services_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
