# Generated by Django 4.0.3 on 2022-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0013_alter_orderservice_paper_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
