# Generated by Django 4.0.3 on 2023-01-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0014_userbase_has_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Выберите фото', upload_to='photos/', verbose_name='order_photo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_order', to='module1.order')),
            ],
        ),
    ]
