# Generated by Django 4.0.3 on 2023-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0015_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_photo',
            name='photo',
            field=models.FileField(help_text='Выберите фото', upload_to='', verbose_name='order_photo'),
        ),
    ]
